name: Compare Screenshot

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

permissions: { }

jobs:
  compare-screenshot-test:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    permissions:
      contents: read
      actions: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'

      - uses: dawidd6/action-download-artifact@246dbf436b23d7c49e21a7ab8204ca9ecd1fe615
        continue-on-error: true
        with:
          name: screenshot
          workflow: StoreScreenshot.yml
          branch: ${{ github.event_name == 'pull_request' && github.event.pull_request.base.ref || github.event.repository.default_branch }}

      - name: compare screenshot test
        id: compare-screenshot-test
        run: |
          ./gradlew compareRoborazziDebug --stacktrace

      - uses: actions/upload-artifact@v3
        if: ${{ always() }}
        with:
          name: screenshot-diff
          path: |
            **/build/outputs/roborazzi
          retention-days: 30

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: screenshot-diff-reports
          path: |
            **/reports
            **/build/outputs/roborazzi
          retention-days: 30

      - uses: actions/upload-artifact@v3
        if: ${{ always() }}
        with:
          name: screenshot-diff-test-results
          path: |
            **/build/test-results
          retention-days: 30

      - name: Save PR number
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          mkdir -p ./pr
          echo ${{ github.event.number }} > ./pr/NR
      - uses: actions/upload-artifact@v3
        with:
          name: pr
          path: pr/