name: Publish Unit Test

on:
  workflow_run:
    workflows:
      - "Android Pull Request CI"
    types:
      - completed

permissions: { }

jobs:
  test-results:
    name: Test Results
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion != 'skipped'
    
    permissions:
      checks: write

      # needed unless run with comment_mode: off
      pull-requests: write

      # only needed for private repository
      contents: read

      # only needed for private repository
      issues: read

      # required by download step to access artifacts API
      actions: read
    
    steps:
      - name: Download and Extract Artifacts
        uses: dawidd6/action-download-artifact@246dbf436b23d7c49e21a7ab8204ca9ecd1fe615
        with:
          run_id: ${{ github.event.workflow_run.id }}
          path: artifacts

      - uses: dawidd6/action-download-artifact@246dbf436b23d7c49e21a7ab8204ca9ecd1fe615
        continue-on-error: true
        with:
          name: screenshot
          workflow: UnitTest.yml
          branch: main

      - name: Upload an event payload for EnricoMi/publish-unit-test-result-action
        uses: actions/upload-artifact@v3
        with:
          name: event-payload
          path: ${{ github.event_path }}

      - run: ./gradlew testDevDebugUnitTest testDebugUnitTest --stacktrace

      - uses: actions/upload-artifact@v3
        if: ${{ always() }}
        with:
          name: screenshot
          path: |
            **/build/outputs/roborazzi
          retention-days: 30

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          commit: ${{ github.event.workflow_run.head_sha }}
          event_file: artifacts/Event File/event.json
          event_name: ${{ github.event.workflow_run.event }}
          files: "artifacts/**/*.xml"