name: UnitTest

on:
  push:
    branches:
      - main
  pull_request:

run-name: "UnitTest by ${{ github.actor }}"

permissions: { }

jobs:
  unit-test:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    permissions:
      contents: read # for clone
      actions: write # for upload-artifact

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'

      - uses: dawidd6/action-download-artifact@246dbf436b23d7c49e21a7ab8204ca9ecd1fe615 # v2.27.0
        continue-on-error: true
        with:
          name: screenshot
          workflow: UnitTest.yml
          branch: main

      - name: Upload an event payload for EnricoMi/publish-unit-test-result-action
        uses: actions/upload-artifact@v3
        with:
          name: event-payload
          path: ${{ github.event_path }}

      - run: ./gradlew testDebugUnitTest --stacktrace

      - uses: actions/upload-artifact@v3
        if: ${{ always() }}
        with:
          name: screenshot
          path: |
            **/build/outputs/roborazzi
          retention-days: 30

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-reports
          path: |
            **/reports
            **/build/outputs/roborazzi

      - id: test-results
        if: always()
        uses: ./.github/actions/upload-distributed-files
        with:
          copy-to: .test-results
          name: "*.xml"
          name-type: file
          grep-by: /test-results/
          artifact-name: 'test-results'
